development:
  adapter: postgresql
  encoding: unicode
  database: tomato_development
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: tomato_production
  pool: 5
  username:
  password:
